apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wafi-app
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/your-username/your-repo.git
    path: /path/to/your/application
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
