apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wafi-app
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/jahswilling/devops-interview.git
    path: /
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAt5nQyMBHfvukiK9kbXDPGrHfBKfnql+Isvy0nM7ApsPtH2qxoeYC
VWINMYKBBZ4bCqSrC5psvGj2GYt1KjmHGF5skxWLmEhDTYdr2kf0Hjl7uJ3RDn9jz/MOTv
dKoR4lJ6cC+Fn8iJ3jSuvYEyAsnD94syus1UcIOP/lT/jXizUsQyp8/W38nxUIWGD525H5
G1bqx9wyuftmAfgJy+ElX2KKwhGFvPeoInXjb6nf6c4CmpxwfM+uBpoNGMd9nG8HlWNp2m
OCPazMgsbucbsUIsjQhaqyI3hUZyAy7TGTUb7RftWphRw0govP6uNLjapnHh3ZJ3FYqEyC
9y7NOd9iaiw1ACq9nAFKE83RaiqN9628J/RrVuAW2Lnz7AMi02R1j3EI6hfOICfBTgThoh
Wt3BkZJ5aJTGy2YRWqzwDJYQ83uaCQn9ON+fyu/UHhgJfknDEWOjgi+mH84VPjR2s8FFOD
Te6sIhqyoFS0XM6XR5hoTyt9ZOMYlPj0gfirz8RNAAAFkNWp/Y3Vqf2NAAAAB3NzaC1yc2
EAAAGBALeZ0MjAR377pIivZG1wzxqx3wSn56pfiLL8tJzOwKbD7R9qsaHmAlViDTGCgQWe
GwqkqwuabLxo9hmLdSo5hxhebJMVi5hIQ02Ha9pH9B45e7id0Q5/Y8/zDk73SqEeJSenAv
hZ/Iid40rr2BMgLJw/eLMrrNVHCDj/5U/414s1LEMqfP1t/J8VCFhg+duR+RtW6sfcMrn7
ZgH4CcvhJV9iisIRhbz3qCJ142+p3+nOApqccHzPrgaaDRjHfZxvB5Vjadpjgj2szILG7n
G7FCLI0IWqsiN4VGcgMu0xk1G+0X7VqYUcNIKLz+rjS42qZx4d2SdxWKhMgvcuzTnfYmos
NQAqvZwBShPN0WoqjfetvCf0a1bgFti58+wDItNkdY9xCOoXziAnwU4E4aIVrdwZGSeWiU
xstmEVqs8AyWEPN7mgkJ/Tjfn8rv1B4YCX5JwxFjo4Ivph/OFT40drPBRTg03urCIasqBU
tFzOl0eYaE8rfWTjGJT49IH4q8/ETQAAAAMBAAEAAAGAK+KfTizvqgGaXXWXCrXJOzdC+I
jtzgKR2T6gKU8eK35vgm/tT6Z77k7Gmov4LRCSpCOiIt7hmNN557c25UXk7cU8LJgcyuSS
+cgh1oYWatcQpJtMaiu2/vC4/dUMSKC8/tJj2lsgCsO6naDr//5Ty3E8d487+6rD42P/Ov
NfCg5GqzNPtwAAP0I2wXFEp+AnbAqFigovMddOla/lH4+McFVMl4C6t+V2ke4d1AYF2Iv+
gVhdZuf5T+iossCUXL0I6it6TglFhHpCa5IqeT3cKhQcPbqlpE7NXjB9BqBqwdZj389/q9
aHctqk9vZ1JgTZ+9SdsrRUL+zAla9JrG9XhC1l9+X5/elfm+yUzWiougsIE9i/Y3pJryC6
VvcwnaAZU7Emy3jYyzLXqGVC3qgxXWvRTEmHGN7lYCy9+DsoYoVG3kDlXlorhOEQmhc3go
7GUIfk7JQavRIAKTu5xA+bDyUljaGjjADNTDRSCV4sAptIdr9SxOb6nXVU8JqrWSt9AAAA
wACTFwf0fwsaoELX45TSFV7+kXjHEA42alQEsHo3wdMT1UdhFZnfLBUm8GQFbpOuf4O4Gu
S6pcloSJrC1ij6se2bnvloKpVOGlALyhiUSvIF1iIQ2YYKSIn1ODCI7QQKmNVeDfRgfKZ0
hV55DgiYG6QiqcPPs9C4qBUd4JC7grPsc1TKcWL5TtlzFZecz09q/g5YG4c+pvs1XX2uj7
mO+eWqQbUH5fJcKTnuDFnU3nOqfJVEGls9wlXhKuZziniNhgAAAMEA5rj2Y+h6KUJLcmn+
QfGfwfCRBBupOiHi2vvdF4hO9J+GXCCdn+0PX6dilhxc2K4lBkACCSfRBWg8gO8bsk2lbz
HJ+pYt+NbVyIAbUH/oj45h9eN5d8M68cyM2Kt3D2/8ML9zs8+uO/Ksg99lnoDMNdkc+TE5
TjE1kckELsKN1GeXMlGR1DQ/kxQNzL+ZHqe5iP6g7ABDbqpWzsljcGzKbz/M8IWreOCi8q
i6ckPZyxA0ixbSfkJAcv51raSGbr0HAAAAwQDLtz07KluLFINrgpLRNZm0bi6kwvbSSbfi
XZQQTlU9tc8+CqOLhxw5OwLFNEraRzg6Tljzmd6jSO9E8lLliVbRKPVJumDu7BFWZZNKpy
Fd7c0IsND8x2+UU8uE/ln+Bfoy1v+bDaoQTfCjCnubVXk2g/1KcRbBnpTo0u6dFkQV1iFp
GIRGLgIVUa+Ar8DPyRii0zE7kkXcd+C4ey/Q06ytQtTtqMh7h0Xmz2sfmf9htbKY05WrMi
qre3pFX7Ng8wsAAAAWcm9vdGNvZGVASmFoc3dpbGxzLU1CUAECAwQF
-----END OPENSSH PRIVATE KEY-----